export * from './get-id/get-id.map-parse'
export * from './get-name/get-name.map-parse'
export * from './get-url/get-url.map-parse'
export * from './get-description/get-description.map-parse'
export * from './get-details/get-details.map-parse'
export * from './get-image/get-image.map-parse'
